[#8] feat: 회원가입 구현 (휴대폰 인증 미완성)
f-lab-edu/gift-card-flea-market pull request #10
Opened 2023-04-29 14:23 UTC by ghm8614

휴대폰 인증을 제외하고 회원가입 기능을 구현했습니다.
- 아이디 중복 체크
- 아이디 중복 Exception 핸들링 
- 비밀번호 암호화 (bcrypt 라이브러리 사용)

2023-04-29 23:15 UTC, f-lab-jason requested changes
음 저는 여기 포함된 주석 전부가 코드에 남길만한 value는 없다고 생각하는데..어떻게 생각하시나요?

2023-04-29 23:15 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/common/GlobalExceptionHandler.java
> +	@ExceptionHandler(NotUniqueUserIdException.class)
nit: `DuplicatedUserIdException` 같은 형태가 더 자주 쓰여요. (부정문보단 긍정문으로 적는게 좀 더 직관적이거든요)

2023-04-29 23:15 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/controller/UserController.java
> +	@GetMapping("/check-duplicate/{userId}")
nit: `/check-duplicated'` or `/check-duplication`
아니면 `/username-availability`같은걸 쓰는곳도 있구요 (구글의 경우)

2023-04-29 23:15 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/controller/UserController.java
> +		userService.checkUserIdDuplicate(userId);
nit: `checkUserIdDuplication`

2023-04-29 23:15 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/dto/request/SignUpRequest.java
> +	@Size(min = 6, max = 12, message = "아이디는 6자리 이상 12자 이하여야 합니다.")
여기 message에서 min과 max값은 annotation에 정의된 파라미터를 그대로 사용할 수 있는데 찾아보시기 바랍니다. (e.g. "...{min}자리 이상 {max}자리 이하...")

2023-04-29 23:15 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/UserService.java
> +		checkUserIdDuplicate(signUpRequest.getUserId());    // 아이디 중복체크
이 아이디 중복체크는 굳이 하지 않아도 될 것 같습니다.
어차피 id가 pk이면 중복되었을 경우 db에서 에러를 던질텐데 그걸로 중복체크도 겸할 수 있으니까요.
현재 로직은 db 호출을 2번하는데 그냥 mapper save만 있을경우 한 번으로 줄일 수 있으니 더 낫다고 생각되고, duplicated 시의 db 에러를 따로 처리해주는게 더 좋을 것 같아요.

2023-04-30 08:39 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/common/GlobalExceptionHandler.java
> +	@ExceptionHandler(NotUniqueUserIdException.class)
코드 작성하면서 배운 내용 정리 및 리뷰어가 코드 리뷰하기에 좀 더 용이하도록 적어봤습니다만, 코드의 이해도를 높이는 주석의 목적과 맞지 않는 것 같습니다. 
앞으로 정리한 내용 및 간략한 설명은 주석이 아닌 PR conversation에 남기겠습니다.

더 직관적인 DuplicatedUserIdException으로 수정하겠습니다.

2023-04-30 08:40 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/controller/UserController.java
> +	@GetMapping("/check-duplicate/{userId}")
check-duplication으로 수정하겠습니다.

2023-04-30 08:40 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/controller/UserController.java
> +		userService.checkUserIdDuplicate(userId);
checkUserIdDuplication로 수정하겠습니다.

2023-04-30 08:41 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/dto/request/SignUpRequest.java
> +	@Size(min = 6, max = 12, message = "아이디는 6자리 이상 12자 이하여야 합니다.")
네 알겠습니다.

2023-05-02 20:33 UTC, f-lab-jason approved these changes

2023-05-02 20:33 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/common/handler/GlobalExceptionHandler.java
> +	}
1. 이거랑 `common/GlobalExceptionHandler`의 차이는 뭔가요? 똑같은게 두 개 있는거 같은데..
2. 
```
	@ExceptionHandler({
		DuplicatedUserIdException.class,
		DuplicatedEmailException.class,
		DuplicatedPhoneException.class
	})
	public ResponseEntity<String> handleDuplicatedExceptions(RuntimeException e) {
		return new ResponseEntity<>(e.getMessage(), HttpStatus.CONFLICT);
	}
```

2023-05-02 20:55 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/common/handler/GlobalExceptionHandler.java
> +	}
1. 커밋에서 제외된 것 같습니다. 수정하겠습니다!
2. 하나의 핸들러로 합치겠습니다.

2023-05-02 20:59 UTC, merged