[#11] feat: 휴대폰 SMS 인증 구현
f-lab-edu/gift-card-flea-market pull request #12
Opened 2023-05-05 08:45 UTC by ghm8614

**네이버 클라우드 플랫폼 SMS API**를 사용해서 **휴대폰 SMS 인증**을 구현했습니다.

- Bean Validation
      - 휴대폰 번호 : 하이픈 없이, 010/011로 시작하는 11자리 
      - 인증 번호 : 6자리
- 인증 번호 발송 성공 시, redis에 저장 
      - Key : 휴대폰 번호
      - Value : 인증 번호
- 인증 번호 timeout 3분 설정

2023-05-05 20:53 UTC, f-lab-jason requested changes
요기도 주석 대부분은 필요없어보이네요.

controller와 service에 대한 unit test도 추가해주시겠어요?

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/dao/SmsVerificationDao.java
> +	private long TIME_OUT;
nit: 시간류의 변수에는 단위도 붙혀주시면 좋습니다. (`TIMEOUT_IN_MILLIS` 같이요)

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +		String jsonStrBody = new ObjectMapper().writeValueAsString(body);
`ObjectMapper`는 상대적으로 생성 비용이 비싼 친구라 bean으로 등록해놓고 주입받도록 하면 좋을 것 같습니다. (thread safe하거든요)

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +		"https://sens.apigw.ntruss.com/sms/v2/services/" + SERVICE_ID + "/messages";
nit: const(private static final)들을 코드 맨위에 놓는게 일반적입니다. `restTemplate`이나 `smsCertificationDao`보다 위에요

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +			throw new SmsSendFailedException("SMS 전송에 실패하였습니다.");
response에 실패 이유는 따로 없나요? exception에 포함되면 좋을 것 같아서요

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +public class SmsVerificationService {
nit: public 코드들을 private 코드들보다 위에 오도록 해주세요 :)

2023-05-05 20:53 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +	private static String makeVerificationCode() {
이건 왜 static으로 선언되어있나요?

2023-05-06 07:02 UTC, ghm8614 commented
네, 불필요한 주석 삭제하고 controller, service 단위 테스트 코드 작성하겠습니다 !

2023-05-06 07:03 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/dao/SmsVerificationDao.java
> +	private long TIME_OUT;
네, 변수 네이밍 수정하겠습니다.

2023-05-06 07:04 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +		"https://sens.apigw.ntruss.com/sms/v2/services/" + SERVICE_ID + "/messages";
private static final 변수 위치 최상단으로 옮겨놓겠습니다.

2023-05-06 07:04 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +public class SmsVerificationService {
네, 알겠습니다!

2023-05-06 07:20 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +	private static String makeVerificationCode() {
슬랙에서 질문했던 내용입니다. 유틸성 메서드를 다른 패키지, 클래스로 옮겨 모아놓아도 되는지 확인받고 적용한다는게.. 삭제를 못한 것 같습니다. 해당 메서드를 포함한 유틸성 메서드들 util 클래스에 모아놓겠습니다.

2023-05-06 08:24 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +		String jsonStrBody = new ObjectMapper().writeValueAsString(body);
네 알겠습니다. new 연산자로 생성하는게 아닌 스프링 빈으로 등록해 주입받아 사용하도록 하겠습니다!

2023-05-06 11:07 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +			throw new SmsSendFailedException("SMS 전송에 실패하였습니다.");
응답 실패의 경우, 네이버 SMS API는 총 6개(400, 401, 403, 404, 429, 500)의 statusCode를 보내줍니다. 이 statusCode를 throw new SmsSendFailedException()의 인자로 넘겨주고 해당 익셉션 핸들러에서 statusCode 별로 분기한 후 알맞은 상태코드와 에러 메시지(실패 이유)를 응답해주도록 하면 될까요?

2023-05-06 22:21 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +			throw new SmsSendFailedException("SMS 전송에 실패하였습니다.");
네, 실패 이유는 response에 따로 없으면 알기는 어려울 것 같고..status code만 말씀하신것처럼 알맞은 상태코드로 mapping시켜주면 좋겠네요.

2023-05-07 05:17 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/user/service/verification/SmsVerificationService.java
> +			throw new SmsSendFailedException("SMS 전송에 실패하였습니다.");
네 알겠습니다!

2023-05-07 18:54 UTC, f-lab-jason approved these changes
아래 리플남긴 부분 정도만 수정하면 좋겠습니다 :)

2023-05-07 18:54 UTC, f-lab-jason commented on src/main/java/com/ghm/giftcardfleamarket/common/handler/GlobalExceptionHandler.java
> +		return new ResponseEntity<>(httpStatus);
e가 가지고있는 에러코드가 HttpStatus 스펙에 맞는 코드면 일일이 분기해주는거 대신에 `HttpStatus.valueOf(e.getErrorCode())`같은 형태로 간단하게 처리할 수 있을텐데 확인해보시겠어요?

2023-05-08 05:09 UTC, ghm8614 commented on src/main/java/com/ghm/giftcardfleamarket/common/handler/GlobalExceptionHandler.java
> +		return new ResponseEntity<>(httpStatus);
HttpStatus enum 클래스에 int 타입의 상태코드를 인자로 받아 enum 상수를 리턴해주는 valueOf(int statusCode) 메서드 확인했습니다. e가 프로퍼티로 가지는 errorCode가 HttpStatus 스펙과 동일하기 때문에, 해당 메서드 적용하겠습니다. 감사합니다 !

2023-05-08 05:26 UTC, merged